name: Build

on: [push, pull_request]

permissions:
  checks: write
  pull-requests: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ pip doxygen
          sudo apt install -y cmake g++ pip doxygen clang clang-tools llvm clang-tidy-15 clang-format-15 libstdc++-12-dev
          pip install conan

      - name: Setup Conan
        run: |
          conan profile detect
          conan install . --output-folder=build --build=missing

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build

      - name: Run Clang-Tidy
        run: |
          clang-tidy -p build $(find . -name '*.cpp') || true

      - name: Run Clang-Format
        run: |
          find compressor libcompressor -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure --output-junit build/test_results.xml

      - name: Publish test results
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: "${{ github.workspace }}/build/build/test_results.xml"
